version: '2'

services:
  ctfd:
    build: .
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro
    depends_on:
      - db
    networks:
        default:
        internal:

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      # for https swap to https.conf and edit this file for url domain
      #- ./conf/nginx/http.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/https.conf:/etc/nginx/nginx.conf      
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - ctfd
    # this command installs new https certs 
    command: "/bin/sh -c 'while :; do sleep 24h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

# https://pentacent.medium.com/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - nginx
    # certbot cert renew every 12 hours.
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  db:
    image: mariadb:10.4.12
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
        internal:

  alphatesting:
    build: ./Challenges/Web/AlphaTesting
    container_name: alphatesting
    restart: always
    ports:
      - 8080:80
  easyone:
      build: ./Challenges/Web/EasyOne
      container_name: easyone
      restart: always
      ports:
          - 8081:80
  ping:
      build: ./Challenges/Web/Ping
      container_name: ping
      restart: always
      ports:
        - 8082:80
  rememberthename:
      build: ./Challenges/Web/RememberTheName
      container_name: rememberthename
      restart: always
      ports:
        - 8083:80
  simpleweblogin:
      build: ./Challenges/Web/SimpleWebLogin
      container_name: simpleweblogin
      restart: always
      ports:
        - 8084:80
  kriegerneedsbettersecurity:
      build: ./Challenges/Passwords/KriegerNeedsBetterSecurity
      container_name: kriegerneedsbettersecurity
      restart: always
      ports:
        - 8085:80
  twohastobebetterthanone:
      build: ./Challenges/Passwords/TwoHasToBeBetterThanOne
      container_name: twohastobebetterthanone
      restart: always
      ports:
        - 8086:80
  querystrings:
      build: ./Challenges/Reversing/QueryStrings
      container_name: querystrings
      restart: always
      ports:
        - 8087:80
  timetrial:
      build: ./Challenges/Network/TimeTrial
      container_name: timetrial
      restart: always
      ports:
        - 8088:80
  speedround:
      build: ./Challenges/Network/SpeedRound
      container_name: speedround
      restart: always
      ports:
        - 10001:10001
  ellipsis:
      build: ./Challenges/Network/Ellipsis
      container_name: ellipsis
      restart: always
      ports:
        - 8095:80

networks:
    default:
    internal:
        internal: true
